import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/Components/Navbar/Navbar'
import Hero from '@/Components/Homepage/Hero/Hero'
import Services from '@/Components/Homepage/Design/Services'
import Footer from '@/Components/Homepage/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Homepage - Farmer buddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <Hero/>
        <Services/>
        <Footer/>
      </main>
    </>
  )
}
