import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/Components/Navbar/Navbar'
import Hero from '@/Components/Homepage/Hero/Hero'
import Services from '@/Components/Homepage/Design/Services'
import Footer from '@/Components/Homepage/Footer/Footer'
import Testimonials from '@/Components/Homepage/Testimonials/testimonials'
import Accordian from '@/Components/Homepage/Accordian/Accordian'


const inter = Inter({ subsets: ['latin'] })

function Home({signOut,user}) {
  return (
    <>
      <Head>
        <title>Homepage - Farmer buddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>

        <Hero/>
        <Services/>
        <Testimonials/>
        <Accordian/>
        <Footer/>
      </main>
    </>
  )
}

export default Home
